/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utscrud;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Akbar
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        getBarang();
        getTransaksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfBarangNama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfBarangHarga = new javax.swing.JTextField();
        btnDEL = new javax.swing.JButton();
        btnADD = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfNamaBarang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfHargaBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfBanyakBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNamaKasir = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dcTanggal = new com.toedter.calendar.JDateChooser();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("APP TOKO DIAMOND");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(480, 0, 130, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 1010, 40);

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TAMBAHKAN TRANSAKSI");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 10, 220, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 60, 240, 40);

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setLayout(null);

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga Barang"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelBarang);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(10, 40, 420, 90);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tabel Barang");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(10, 10, 220, 30);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama Barang");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(440, 10, 220, 30);

        tfBarangNama.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        jPanel5.add(tfBarangNama);
        tfBarangNama.setBounds(440, 40, 220, 30);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Harga Barang");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(440, 70, 220, 30);

        tfBarangHarga.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        jPanel5.add(tfBarangHarga);
        tfBarangHarga.setBounds(440, 100, 220, 30);

        btnDEL.setText("DELETE");
        btnDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELActionPerformed(evt);
            }
        });
        jPanel5.add(btnDEL);
        btnDEL.setBounds(670, 100, 80, 30);

        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });
        jPanel5.add(btnADD);
        btnADD.setBounds(670, 60, 80, 30);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(260, 60, 760, 140);

        jPanel6.setBackground(new java.awt.Color(102, 102, 255));
        jPanel6.setLayout(null);

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Transaksi", "Nama Kasir", "Tanggal", "Nama Barang", "Harga Barang", "Banyak Barang", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(10, 52, 740, 240);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("*Diskon 30000 untuk setiap pembeliaan diatas 100000");
        jPanel6.add(jLabel1);
        jLabel1.setBounds(250, 20, 330, 30);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tabel Transaksi");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(10, 20, 220, 30);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(260, 210, 760, 310);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setLayout(null);

        tfNamaBarang.setEditable(false);
        tfNamaBarang.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        jPanel3.add(tfNamaBarang);
        tfNamaBarang.setBounds(10, 40, 220, 30);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Harga Barang");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 70, 220, 30);

        tfHargaBarang.setEditable(false);
        tfHargaBarang.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        jPanel3.add(tfHargaBarang);
        tfHargaBarang.setBounds(10, 100, 220, 30);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Banyak Barang");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 130, 220, 30);

        tfBanyakBarang.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        jPanel3.add(tfBanyakBarang);
        tfBanyakBarang.setBounds(10, 160, 220, 30);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Kasir");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 190, 220, 30);

        tfNamaKasir.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        jPanel3.add(tfNamaKasir);
        tfNamaKasir.setBounds(10, 220, 220, 30);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tanggal");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 250, 220, 30);
        jPanel3.add(dcTanggal);
        dcTanggal.setBounds(10, 280, 220, 30);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave);
        btnSave.setBounds(10, 320, 100, 30);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);
        btnDelete.setBounds(130, 320, 100, 30);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel3.add(btnClear);
        btnClear.setBounds(10, 360, 100, 30);

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel3.add(btnPrint);
        btnPrint.setBounds(130, 360, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Barang");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 10, 220, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 110, 240, 410);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1040, 530);

        setBounds(0, 0, 1043, 569);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        int baris = tabelBarang.getSelectedRow();
        if(baris!= -1){
          tfNamaBarang.setText(tabelBarang.getValueAt(baris, 1).toString());
          tfHargaBarang.setText(tabelBarang.getValueAt(baris, 2).toString());
        }
    }//GEN-LAST:event_tabelBarangMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(dcTanggal.getDate());
        int harga = Integer.parseInt(tfHargaBarang.getText());
        int banyak = Integer.parseInt(tfBanyakBarang.getText());
        int totalharga = harga * banyak;
        
        if(totalharga>100000){
            totalharga = totalharga - 30000;
        }
        
        if ("".equals(tfNamaBarang.getText())||"".equals(tfHargaBarang.getText())||"".equals(tfBanyakBarang.getText())||"".equals(tfNamaKasir.getText())||"".equals(tanggal)){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else{
        String SQL = "INSERT INTO tb_transaksi(id_transaksi, nama_kasir, tanggal, nama_barang, harga_barang, banyak_barang, total) " + "VALUES(NULL,'"+tfNamaKasir.getText()+"','"+tanggal+"','"+tfNamaBarang.getText()+"','"+tfHargaBarang.getText()+"','"+tfBanyakBarang.getText()+"','"+totalharga+"')";
         int status = DBConnection.execute(SQL);
         if (status == 1){
             JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
             getBarang();
             getTransaksi();
         }
         else{
             JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
         }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       int baris = tableTransaksi.getSelectedRow();
        if (baris != -1){
            String id_transaksi = tableTransaksi.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_transaksi WHERE id_transaksi='"+id_transaksi+"'";
            int status = DBConnection.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                getBarang();
                getTransaksi();
            } else{
                JOptionPane.showMessageDialog(this, "Data Gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris terlebih dahulu sebelum menghapus", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
        int baris = tableTransaksi.getSelectedRow();
        if(baris!= -1){
          tfNamaBarang.setText(tableTransaksi.getValueAt(baris, 3).toString());
          tfHargaBarang.setText(tableTransaksi.getValueAt(baris, 4).toString());
          tfBanyakBarang.setText(tableTransaksi.getValueAt(baris, 5).toString());
          tfNamaKasir.setText(tableTransaksi.getValueAt(baris, 1).toString());
          SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try {
            dateFormat = date.parse(tableTransaksi.getValueAt(baris, 2).toString());
            } catch (ParseException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }

            dcTanggal.setDate(dateFormat);
        }
    }//GEN-LAST:event_tableTransaksiMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
      tfNamaBarang.setText("");
      tfHargaBarang.setText("");
      tfBanyakBarang.setText("");
      dcTanggal.setDate(null);
      tfNamaKasir.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header = new MessageFormat("TRANSAKSI TOKO DIAMOND");
       MessageFormat footer = new MessageFormat("Page {0,number,integer}");
       
       try {
           tableTransaksi.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
       } catch (java.awt.print.PrinterException e) {
           System.err.format("Cannot Print %s&n", e.getMessage());
       } 
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        
        
        if ("".equals(tfBarangNama.getText())||"".equals(tfBarangHarga.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else{
        String SQL = "INSERT INTO tb_barang(id_barang, nama_barang, harga_barang) " + "VALUES(NULL,'"+tfBarangNama.getText()+"','"+tfBarangHarga.getText()+"')";
         int status = DBConnection.execute(SQL);
         if (status == 1){
             JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
             getBarang();
             getTransaksi();
         }
         else{
             JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
         }
        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void btnDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELActionPerformed
        int baris = tabelBarang.getSelectedRow();
        if (baris != -1){
            String id_barang = tabelBarang.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_barang WHERE id_barang='"+id_barang+"'";
            int status = DBConnection.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                getBarang();
                getTransaksi();
            } else{
                JOptionPane.showMessageDialog(this, "Data Gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris terlebih dahulu sebelum menghapus", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDEL;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser dcTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JTextField tfBanyakBarang;
    private javax.swing.JTextField tfBarangHarga;
    private javax.swing.JTextField tfBarangNama;
    private javax.swing.JTextField tfHargaBarang;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfNamaKasir;
    // End of variables declaration//GEN-END:variables

    private void getBarang() {
     String kolom[] = {"Kode Barang","Nama Barang","Harga Barang"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM `tb_barang`";
        ResultSet rs = DBConnection.executeQuery(SQL);
        try {
            while(rs.next()){
                String id_barang = rs.getString(1);
                String nama_barang = rs.getString(2);
                String harga_barang = rs.getString(3);
                String data[] = {id_barang, nama_barang, harga_barang};
                dtm.addRow(data);
            }
        } catch(SQLException ex){
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabelBarang.setModel(dtm);    
    }

    private void getTransaksi() {
        String kolom[] = {"Kode Transaksi", "Nama Kasir", "Tanggal", "Nama Barang", "Harga Barang", "Banyak Barang", "Total"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM `tb_transaksi`";
        ResultSet rs = DBConnection.executeQuery(SQL);
        try {
            while(rs.next()){
                String id_transaksi = rs.getString(1);
                String nama_kasir = rs.getString(2);
                String tanggal = rs.getString(3);
                String nama_barang = rs.getString(4);
                String harga_barang = rs.getString(5);
                String banyak_barang = rs.getString(6);
                String total = rs.getString(7);
                String data[] = {id_transaksi, nama_kasir, tanggal, nama_barang, harga_barang, banyak_barang, total};
                dtm.addRow(data);
            }
        } catch(SQLException ex){
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        tableTransaksi.setModel(dtm);  
    }
}
